version: '3.8'

services:
  stock-mcp:
    build: .
    container_name: stock-mcp-server
    environment:
      - NODE_ENV=production
      - ALPACA_KEY=${ALPACA_KEY}
      - ALPACA_SECRET=${ALPACA_SECRET}
    env_file:
      - .env
    stdin_open: true    # Keep stdin open for MCP communication
    tty: true          # Allocate a pseudo-TTY
    restart: unless-stopped
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge 